---
float32 sx
float32 sy
float32 sz	
float32 dx
float32 dy
float32 dz
float32 b1x
float32 b1y
float32 b1z
float32 b2x
float32 b2y
float32 b2z
float32 b3x
float32 b3y
float32 b3z
float32 b4x
float32 b4y
float32 b4z